apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-server
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app
      

