apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-prod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-prod
      labels:
        name: result-app-prod
        app: demo-voting-app     
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80